name: update
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - uses: hustcer/setup-nu@0bf8d70d627bc80197a73473468c42c037351f6b
      with:
        version: "0.101.0"
      env:
        # default runner token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: nu habitica.nu
      env:
        # dedicated token with gist permission
        GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: 5992940f1f9bbc9114f88d7877247331
        HABITICA_API_USER: ${{ secrets.HABITICA_API_USER }}
        HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
